### ISSUE TITLE
Export to:do: style methods from modules

### ISSUE THREAD

**Issue by ghost** [gokr/spryvm#3]
I'm not sure what the term for this method style is, but I cannot figure out how to export and call the `'to:do:` example from a module.

If I create a module like this:
```
{
  _meta = {
    name = 'Foo
    version = "1.0"
    description = "Testing module closure"
  }

  'to:do: = method [:to :block
    n = self
    [n <= to] whileTrue: [
      do block n
      ..n = (n + 1)]]

}
```

How do I call `to:do:` from the root scope? `Foo::to: x do: y` does not work.

**Comment by gokr** [comment]
Will take a look at this - the modules stuff was not really tested etc

**Comment by gokr** [comment]
I have now given the modules stuff an overhaul so that it works at least "basically". See the `examples/modules`. It uses "assert" from sprylib.nim also that I tweaked. One issue remains as duly noted and that is the fact that you can't use a "module get word" with the "::" syntax together with keywords, that... seems like it should be fixable.

**Comment by gokr** [comment]
Closing this one, created #7
